version: '3.9'
services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root_pass'
      MYSQL_DATABASE: app_db
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysqlsrv
